### ISSUE TITLE
py-mc workflow diagram

### ISSUE THREAD

**Issue by fdebonneval** [dgarros/py-metric-collector#17]
Hi,

I'd like to include something more visual to the README, what do you think of this ?

Thanks,
F

<img width="879" alt="capture d ecran 2018-08-31 a 22 16 48" src="https://user-images.githubusercontent.com/5792255/44934163-1c706000-ad6c-11e8-9d20-d4c5cff7b07b.png">

**Comment by dgarros** [comment]
Agreed, something visual would be great

Might be good to add another TSDB like Prometheus to highlight that we selected telegraf because it decouple the collector from the database.

Also, not sure how to represent that but, it might be interesting to highlight that the collector can work with both static or dynamic inventory

**Comment by fdebonneval** [comment]
![py-mc](https://user-images.githubusercontent.com/5792255/45218573-63001600-b2a8-11e8-9259-348b9fa05ef2.png)

Better ?

**Comment by dgarros** [comment]
@fdebonneval sorry I never replied to your last message
Looks absolutely better, thanks for doing it.
